export const GET_VIDEOGAMES = "GET_VIDEOGAMES";

export const GET_VIDEOGAMES_BY_NAME = "GET_VIDEOGAMES_BY_NAME";

export const GET_VIDEOGAME_BY_ID = "GET_VIDEOGAME_BY_ID";

export const CLEAR_DETAIL = "CLEAR_DETAIL";

export const HANDLE_MESSAGE = 'HANDLE_MESSAGE';

export const NOT_GET_VIDEOGAME_BY_NAME = "NOT_GET_VIDEOGAME_BY_NAME";